set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR pi32v2)

if(CONFIG_CHIP_CHOICE STREQUAL "wl82")
    set(JIELI_CPU wl82)
    set(JIELI_SDK_PROBE "apps/demo/demo_hello/board/wl82/Makefile")
elseif(CONFIG_CHIP_CHOICE STREQUAL "wl83")
    set(JIELI_CPU wl83)
    set(JIELI_SDK_PROBE "apps/demo/demo_hello/board/wl83/Makefile")
else()
    message(FATAL_ERROR "JIELI requires CONFIG_CHIP_CHOICE to be wl82 or wl83")
endif()

if(DEFINED ENV{JIELI_SDK_ROOT})
    set(JIELI_SDK_ROOT "$ENV{JIELI_SDK_ROOT}")
elseif(CONFIG_CHIP_CHOICE STREQUAL "wl83" AND EXISTS "${PLATFORM_PATH}/chip/wl83/AC792_SDK/sdk/Makefile")
    set(JIELI_SDK_ROOT "${PLATFORM_PATH}/chip/wl83/AC792_SDK/sdk")
elseif(CONFIG_CHIP_CHOICE STREQUAL "wl82" AND EXISTS "${PLATFORM_PATH}/chip/wl82/AC79_AIoT_SDK")
    set(JIELI_SDK_ROOT "${PLATFORM_PATH}/chip/wl82/AC79_AIoT_SDK")
elseif(CONFIG_CHIP_CHOICE STREQUAL "wl82" AND EXISTS "${PLATFORM_PATH}/AC79_AIoT_SDK")
    set(JIELI_SDK_ROOT "${PLATFORM_PATH}/AC79_AIoT_SDK")
else()
    if(CONFIG_CHIP_CHOICE STREQUAL "wl82")
        set(JIELI_SDK_ROOT "${PLATFORM_PATH}/../../../AC79_AIoT_SDK")
    else()
        message(FATAL_ERROR "WL83 SDK not found under ${PLATFORM_PATH}")
    endif()
endif()
if(NOT EXISTS "${JIELI_SDK_ROOT}/${JIELI_SDK_PROBE}")
    message(FATAL_ERROR
        "Jieli SDK profile does not match CONFIG_CHIP_CHOICE=${CONFIG_CHIP_CHOICE}: ${JIELI_SDK_ROOT}")
endif()
string(TOUPPER "${JIELI_CPU}" JIELI_CPU_DEFINE)
file(TO_CMAKE_PATH "${JIELI_SDK_ROOT}" JIELI_SDK_ROOT)
set(JIELI_SDK_ROOT "${JIELI_SDK_ROOT}" CACHE PATH "JieLi SDK root" FORCE)

function(_jieli_toolchain_find_tool tool_dir logical_name output)
    if(CMAKE_HOST_WIN32)
        if(logical_name STREQUAL "clang")
            set(names clang.exe clang)
        elseif(logical_name STREQUAL "lto-wrapper")
            set(names lto-wrapper.exe lto-wrapper pi32v2-lto-wrapper.exe pi32v2-lto-wrapper)
        elseif(logical_name STREQUAL "lto-ar")
            set(names lto-ar.exe lto-ar pi32v2-lto-ar.exe pi32v2-lto-ar)
        elseif(logical_name STREQUAL "objdump")
            set(names objdump.exe objdump llvm-objdump.exe llvm-objdump)
        elseif(logical_name STREQUAL "objsizedump")
            set(names objsizedump.exe objsizedump llvm-objsizedump.exe llvm-objsizedump)
        endif()
    else()
        if(logical_name STREQUAL "clang")
            set(names clang)
        elseif(logical_name STREQUAL "lto-wrapper")
            set(names lto-wrapper pi32v2-lto-wrapper)
        elseif(logical_name STREQUAL "lto-ar")
            set(names lto-ar pi32v2-lto-ar)
        elseif(logical_name STREQUAL "objdump")
            set(names objdump llvm-objdump)
        elseif(logical_name STREQUAL "objsizedump")
            set(names objsizedump llvm-objsizedump)
        endif()
    endif()

    foreach(name IN LISTS names)
        if(EXISTS "${tool_dir}/${name}")
            set(${output} "${tool_dir}/${name}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${output} "" PARENT_SCOPE)
endfunction()

function(_jieli_toolchain_missing_tools tool_dir output)
    set(missing)
    foreach(logical_name clang lto-wrapper lto-ar objdump objsizedump)
        _jieli_toolchain_find_tool("${tool_dir}" "${logical_name}" tool_path)
        if(NOT tool_path)
            list(APPEND missing "${logical_name}")
        endif()
    endforeach()
    set(${output} "${missing}" PARENT_SCOPE)
endfunction()

if(DEFINED ENV{JIELI_TOOL_DIR})
    set(JIELI_TOOL_DIR "$ENV{JIELI_TOOL_DIR}")
    if(NOT JIELI_TOOL_DIR)
        message(FATAL_ERROR "JIELI_TOOL_DIR is set but empty; unset it or set pi32v2/bin.")
    endif()
    _jieli_toolchain_missing_tools("${JIELI_TOOL_DIR}" missing_tools)
    if(missing_tools)
        message(FATAL_ERROR
            "JIELI_TOOL_DIR is set to '$ENV{JIELI_TOOL_DIR}' but is missing required tools: "
            "${missing_tools}. Correct JIELI_TOOL_DIR or unset it to use automatic discovery.")
    endif()
elseif(CMAKE_HOST_WIN32)
    set(portable_tool_dir "${PLATFORM_PATH}/.tools/portable-jieli-windows/pi32/bin")
    _jieli_toolchain_missing_tools("${portable_tool_dir}" portable_missing_tools)
    if(NOT portable_missing_tools)
        set(JIELI_TOOL_DIR "${portable_tool_dir}")
    else()
        _jieli_toolchain_missing_tools("C:/JL/pi32/bin" system_missing_tools)
        if(NOT system_missing_tools)
            set(JIELI_TOOL_DIR "C:/JL/pi32/bin")
        endif()
    endif()
endif()

if(NOT JIELI_TOOL_DIR)
    set(sdk_tool_dir "${JIELI_SDK_ROOT}/../ipc_ac7916a/toolchain/jieli-linux-toolchains/pi32v2/bin")
    _jieli_toolchain_missing_tools("${sdk_tool_dir}" sdk_missing_tools)
    if(NOT sdk_missing_tools)
        set(JIELI_TOOL_DIR "${sdk_tool_dir}")
    elseif(NOT CMAKE_HOST_WIN32)
        _jieli_toolchain_missing_tools("/opt/jieli/pi32v2/bin" opt_missing_tools)
        if(NOT opt_missing_tools)
            set(JIELI_TOOL_DIR "/opt/jieli/pi32v2/bin")
        endif()
    endif()
endif()

if(NOT JIELI_TOOL_DIR)
    set(JIELI_TOOL_DIR "${PLATFORM_PATH}/../../jieli-toolchain/pi32v2/bin")
    _jieli_toolchain_missing_tools("${JIELI_TOOL_DIR}" missing_tools)
    if(missing_tools)
        message(FATAL_ERROR
            "Jieli pi32v2 toolchain not found. Required tools: clang, lto-wrapper, lto-ar, "
            "objdump, objsizedump. Set JIELI_TOOL_DIR or prepare "
            ".tools/portable-jieli-windows/pi32/bin on Windows.")
    endif()
endif()
file(TO_CMAKE_PATH "${JIELI_TOOL_DIR}" JIELI_TOOL_DIR)

if(CMAKE_HOST_WIN32)
    set(CMAKE_AR "${PLATFORM_PATH}/jieli_llvm_ar.cmd")
    set(CMAKE_RANLIB "${PLATFORM_PATH}/jieli_ranlib.cmd")
else()
    set(CMAKE_AR "${JIELI_TOOL_DIR}/lto-ar")
    set(CMAKE_RANLIB "${PLATFORM_PATH}/jieli_ranlib.sh")
endif()
_jieli_toolchain_find_tool("${JIELI_TOOL_DIR}" clang JIELI_CLANG)
if(NOT JIELI_CLANG)
    message(FATAL_ERROR "Jieli clang not found in selected toolchain: ${JIELI_TOOL_DIR}")
endif()
set(CMAKE_C_COMPILER "${JIELI_CLANG}")
set(CMAKE_CXX_COMPILER "${JIELI_CLANG}")

set(JIELI_NEWLIB_INCLUDE "${JIELI_SDK_ROOT}/include_lib/newlib/include")
set(JIELI_CPP_INCLUDE "${JIELI_SDK_ROOT}/include_lib/c++/include")
set(JIELI_C_INCLUDE_FLAGS "-isystem${JIELI_NEWLIB_INCLUDE}")
set(JIELI_CXX_INCLUDE_FLAGS
    "-isystem${JIELI_NEWLIB_INCLUDE} -isystem${JIELI_CPP_INCLUDE}")
set(JIELI_COMMON_DEFINES
    "-DCONFIG_CPU_${JIELI_CPU_DEFINE} -DJIELI_SELECTED_CHIP_${JIELI_CPU_DEFINE}=1 -DCONFIG_FREE_RTOS_ENABLE -DCONFIG_THREAD_ENABLE -DBOOL_DEFINE_CONFLICT -DMBEDTLS_TCPIP_LWIP -D_GNU_SOURCE -D_XOPEN_SOURCE=700 -D__ELF__")

set(CMAKE_C_FLAGS
    "-target pi32v2 -integrated-as -mcpu=r3 -mfprev1 -Oz -flto -fno-common -ffunction-sections -fdata-sections -fno-unwind-tables -include stdbool.h -D__GCC_PI32V2__ ${JIELI_COMMON_DEFINES} ${JIELI_C_INCLUDE_FLAGS}")
set(CMAKE_CXX_FLAGS
    "-target pi32v2 -integrated-as -mcpu=r3 -mfprev1 -Oz -flto -fno-common -ffunction-sections -fdata-sections -fno-unwind-tables -fno-exceptions -fno-rtti -std=gnu++14 -D__GCC_PI32V2__ ${JIELI_COMMON_DEFINES} ${JIELI_CXX_INCLUDE_FLAGS}")

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
